const data = [
  /*   `El sol s'amagava darrere dels turons quan la Martina va arribar a la petita vila de muntanya on havia decidit passar uns dies per desconectar de la feina i la ciutat. Amb el seu equipatge a l'esquena, va caminar fins a la casa rural que havia reservat per internet, una antiga masia de pedra amb vistes a la vall.
  El propietari de la casa, en Miquel, la va rebre amb un somriure i li va ensenyar la seva habitació, amb una gran finestra des d'on es podia veure el bosc i la muntanya. La Martina va deixar la seva motxilla a un racó i va sortir al pati, on unes gallines picotejaven el sòl.
  La vida a la vila era tranquil·la i pausada, sense sorolls ni presses. La Martina va passar els primers dies fent excursions per la muntanya, respirant aire pur i descobrint paisatges espectaculars. A les tardes, llegia al balcó de la seva habitació, amb una tassa de te i unes galetes que havia comprat al forn del poble.
  Una nit, mentre sopava a la terrassa d'un restaurant del poble, la Martina va conèixer en Joan, un jove de la vila que treballava a la fàbrica de formatge del seu oncle. Van parlar de les seves vides, les seves aficions i les seves preocupacions.`,
  ` En Joan li va ensenyar alguns racons del poble que ella no havia descobert encara.
  A mesura que passaven els dies, la Martina i en Joan es van veure més sovint. Van fer caminades junts, van passejar pel riu i van anar a escoltar música en directe a la plaça del poble. Amb el temps, van començar a sentir una atracció l'un per l'altre, però no van voler afanyar les coses.
  Una nit, després d'un sopar a la casa de la la Martina, van seure al balcó i van veure les estrelles. En Joan li va confessar que havia estat enamorat d'ella des del primer dia, però que no volia pressionar-la. La Martina es va emocionar i li va confessar que ella també sentia alguna cosa per ell.
  Els dies van passar ràpids i, abans que s'adonessin, havien passat dues setmanes a la vila. La Martina i en Joan van decidir que volien intentar una relació a distància i es van intercanviar números de telèfon i adreces de correu electrònic. Es van besar acomiadant-se a l'estació de tren i van prometre mantenir el contacte.
  la Martina va tornar a la ciutat amb el cor ple d'emocions. La seva estada a la vila havia estat un respir d'aire fresc enmig de la seva vida estressant i havia conegut a una persona especial que, malgrat la distància, volia intentar-ho amb ella. Va prometre tornar a la vila, de ben segur.`,
  `Era una vegada un grup de lingüistes que estudiaven la fonètica. Van descobrir que hi havia una paraula en particular que era bastant interessant: «stewardesses». Aquesta paraula, segons van descobrir, és el mot més llarg que es pot escriure utilitzant únicament les tecles de la fila superior del teclat d'un ordinador QWERTY. Els lingüistes van estar molt entusiasmats amb aquesta descoberta i van començar a buscar altres paraules curioses que poguessin ser escrites només amb les tecles d'una fila del teclat.`,
 
  `Era una vegada un grup de lingüistes que estudiaven la fonètica. Van descobrir que hi havia una paraula en particular que era bastant interessant: «stewardesses». Aquesta paraula, segons van descobrir, és el mot més llarg que es pot escriure utilitzant únicament les tecles de la fila superior del teclat d'un ordinador QWERTY. Els lingüistes van estar molt entusiasmats amb aquesta descoberta i van començar a buscar altres paraules curioses que poguessin ser escrites només amb les tecles d'una fila del teclat. Un cop van trobar «stewardesses», els lingüistes van començar a jugar amb el teclat. Van experimentar amb altres paraules, però no n'hi havia cap altre que fos tan llarg com «stewardesses». Van decidir que això deuria ser perquè les tecles en la fila superior del teclat són les que es fan servir més per escriure les paraules més comunes de l'anglès`, 
  `Amb el temps, aquesta curiositat lingüística va començar a circular per internet i, sense saber com, es va convertir en un repte: trobar altres paraules que fossin també tan llargues com «stewardesses» i que només fessin servir les tecles d'una fila del teclat. La gent va començar a buscar i van trobar algunes paraules força curioses com «poppadums», un plat indi, o «reverberated», que significa «rebotejar». L'èxit d'aquesta cerca va fer que sorgissin altres reptes similars, com per exemple trobar paraules que utilitzessin totes les tecles del teclat. La curiositat dels lingüistes va encendre la imaginació de molta gent, i així va sorgir un joc anomenat «Typing Maniac». Es tracta d'un joc en línia en el qual has d'escriure paraules el més ràpid possible. El joc es basa en la mateixa idea que la paraula «stewardesses» i consisteix a escriure el més ràpid possible paraules que només fac  in servir les tecles d'una fila del teclat. El joc va començar a tenir molta popularitat i encara és possible trobar versions en línia actuals. En conclusió, una curiositat lingüística va despertar la imaginació de moltes persones i es va convertir en un repte a internet. La paraula «stewardesses» va obrir una porta cap a altres paraules curioses que utilitzen les tecles d'una sola fila del teclat. Va convertir-se en un joc en línia, que encara és popular avui. La curiositat humana pot ser realment sorprenent, i una paraula podria ser l'origen de moltes altres descobertes lingüístiques!`,
  
  
  `En la llengua, hi ha molts aspectes interessants i fascinants que sovint passen desapercebuts. Una d'aquestes curiositats és l'origen de les paraules i com s'han format al llarg del temps. A vegades, una paraula que fem servir avui en dia va ser creat per casualitat o per una mena de joc de paraules que es va fer popular. Així és com va néixer la paraula "serendipitat".

  La paraula "serendipitat" va ser creada pel poeta i escriptor anglès Horace Walpole al segle XVIII. Va inventar la paraula després d'una anècdota que va viure en la qual va descobrir per casualitat una pintura que buscava, sense haver-la cercada. Va descriure aquest descobriment com una "serendipitat" i va crear la paraula combinant "Serendip", un nom antic per a l'illa de Sri Lanka, i la paraula "feliç coincidència"`,

  `Això és només un exemple de com les paraules poden ser creades per casualitat. Un altre exemple és la paraula "quark", que és una de les partícules fonamentals de la física. El físic Murray Gell-Mann va explicar que va trobar la paraula en la novel·la de James Joyce "Finnegan's Wake". D'altra banda, les paraules també poden ser creades per jocs de paraules o trompes de mots. Un exemple d'això és la paraula "spork", que combina els mots "cullera" i "forquilla". La paraula es va popularitzar a la dècada de 1950, amb la introducció de culleres i forquilles combinades en els menjadors escolars americans. Les paraules també poden ser creades a través de l'adaptació d'altres idiomes`,
  

  `Una de les coses més interessants de la llengua és la seva capacitat per canviar i evolucionar amb el temps. Una forma en què es manifesta aquesta evolució és a través de l'ús i l'adopció de paraules d'altres idiomes. Això es coneix com a préstec lingüístic i és un fenomen comú en totes les llengües. El català no és una excepció, i té un bon nombre de paraules que provenen d'altres idiomes. Un exemple de préstec lingüístic al català són les paraules que provenen del llatí. Aproximadament un 70% del vocabulari català prové del llatí. Això es deu a la influència de la llengua llatina en la cultura europea durant molts anys`,
  
`Paraules com "amic", "mare", "poma" i "foc" són algunes paraules del català que tenen arrels llatines. Una altre exemple interessant de préstec lingüístic són les paraules que provenen de l'àrab. Durant els segles VIII i XI, la península ibèrica estava en mans dels àrabs. Aquesta influència es veu reflectida en el català a través de paraules com "alberg", "alcalde" i "almirall." Aquests mots aporten una visió interessant del passat històric de la llengua. Alguns préstecs lingüístics no són tan evidents, i la gent pot ignorar que algunes paraules vénen d'un altre idioma. Per exemple, molta gent no sap que la paraula "xocolata" prové del nàhuatl, la llengua que es parlava pels indis a l'Amèrica Central abans de la conquesta espanyola. Això demostra que la llengua és més complexa del que la majoria de la gent pot imaginar, i que les paraules poden tenir molts orígens diferents. Tot i que als puristes de la llengua podria no agradar-los la idea de préstecs lingüístics, són part d'un procés natural d'evolució lingüística. De fet, moltes paraules que ara considerem "natives" del català es van adoptar en moments diferents de la seva història de l'adopció de paraules d'altres idiomes. Com la llengua continua evolucionant i es barreja amb altres cultures i idiomes, és probable que el nombre de préstecs lingüístics continui creixent`,
*/
`Benvinguts a l'antic Egipte, un país ple de misteris i fascinants històries. Els egipcis eren una civilització molt avançada en la seva època, amb una cultura rica i complexa que encara avui ens deixa sorpresos.

La civilització egípcia va començar fa més de 5000 anys, a la vall del riu Nil. Els egipcis van desenvolupar una gran varietat de tècniques agrícoles per aprofitar la fertilitat del riu, i van construir nombroses infraestructures, com preses i canals, per controlar les inundacions.

Una de les característiques més importants de la cultura egípcia eren les seves piràmides, construccions enormes conegudes per ser tombes dels faraons, els reis d'Egipte, i els seus familiars. Les piràmides eren construïdes amb pedres enormes i les seves formes estaven inspirades en les llums del sol i de la lluna.

Els egipcis també creien en la vida després de la mort i tenien una gran varietat de deus que protegien i ajudaven a les persones en la seva vida diària. La religió era una part important de la seva cultura, i moltes de les seves creences i rituals encara s'utilitzen avui en dia.

Finalment, l'antic Egipte va caure en la conquesta dels romans l'any 30 aC, però la seva cultura i les seves històries continuen sent un element important de la història mundial. La civilització egípcia ens va deixar un llegat impressionant, que encara avui en dia ens fascina i ens inspira`,
];
/*  .replaceAll("—", "\n-") */

function getData() {
  var rannum = Math.floor(Math.random() * data.length);
  /*   console.log(data[rannum]);
  console.log(data[rannum].split(/;\s|\.\s/)); */
  return data[rannum].split(/;\s|\.\s/);
}

export default getData;
