import React, { useState } from "react";
import styled from "styled-components";

const dataCAST = [
 
  ["Niños", "Simple"],
  ["Sillita", "Derivada"],
  ["Baloncesto", "Compuesta"],
  ["Desalmado", "Parasintética por derivación"],
  ["Multimillonario", "Compuesta"],
  ["Bicicleta", "Derivada"],
  ["Librero", "Derivada"],
  ["Zapatería", "Derivada"],
  ["Jardinero", "Derivada"],
  ["Cocinero", "Derivada"],
  ["Llamar", "Simple"],
  ["Casa", "Primitiva"],
  ["Mesa", "Primitiva"],
  ["Árbol", "Primitiva"],
  ["Agua", "Primitiva"],
  ["Sol", "Primitiva"],
  ["Silla", "Primitiva"],
  ["Tierra", "Primitiva"],
  ["Mar", "Primitiva"],
  ["Cielo", "Primitiva"],
  ["Fuego", "Primitiva"],
  ["Pan", "Primitiva"],
  ["Piedra", "Primitiva"],
  ["Luz", "Primitiva"],
  ["Flor", "Primitiva"],
  ["Montaña", "Primitiva"],
  ["Río", "Primitiva"],
  ["Viento", "Primitiva"],
  ["Estrella", "Primitiva"],
  ["Nube", "Primitiva"],
  ["Nieve", "Primitiva"],
  ["Camino", "Primitiva"],
  ["Lluvia", "Primitiva"],
  ["Ola", "Primitiva"],
  ["Sol", "Primitiva"],
  ["Luna", "Primitiva"],
  ["Hielo", "Primitiva"],
  ["Tierra", "Primitiva"],
  ["Aire", "Primitiva"],
  ["Marea", "Primitiva"],
  ["Barro", "Primitiva"],
  ["Pasto", "Primitiva"],
  ["Arena", "Primitiva"],
  ["Agua", "Primitiva"],
  ["Amarillo", "Primitiva"],
  ["Árbol", "Primitiva"],
  ["Azul", "Primitiva"],
  ["Blanco", "Primitiva"],
  ["Casa", "Primitiva"],
  ["Cuerpo", "Primitiva"],
  ["Diente", "Primitiva"],
  ["Gato", "Primitiva"],
  ["León", "Primitiva"],
  ["Lobo", "Primitiva"],
  ["Madera", "Primitiva"],
  ["Mesa", "Primitiva"],
  ["Miel", "Primitiva"],
  ["Naranja", "Primitiva"],
  ["Nuez", "Primitiva"],
  ["Oro", "Primitiva"],
  ["Pájaro", "Primitiva"],
  ["Plata", "Primitiva"],
  ["Puerta", "Primitiva"],
  ["Ratón", "Primitiva"],
  ["Rojo", "Primitiva"],
  ["Soltero", "Primitiva"],
  ["Tigre", "Primitiva"],
  ["Vaca", "Primitiva"],
  ["Aire", "Primitiva"],
  ["Alma", "Primitiva"],
  ["Ángel", "Primitiva"],
  ["Arena", "Primitiva"],
  ["Arco", "Primitiva"],
  ["Árido", "Primitiva"],
  ["Ave", "Primitiva"],
  ["Barro", "Primitiva"],
  ["Bosque", "Primitiva"],
  ["Cielo", "Primitiva"],
  ["Cobre", "Primitiva"],
  ["Cola", "Primitiva"],
  ["Cuerda", "Primitiva"],
  ["Estrella", "Primitiva"],
  ["Fuego", "Primitiva"],
  ["Hielo", "Primitiva"],
  ["Hierro", "Primitiva"],
  ["Luna", "Primitiva"],
  ["Miel", "Primitiva"],
  ["Montaña", "Primitiva"],
  ["Niebla", "Primitiva"],
  ["Ojo", "Primitiva"],
  ["Ola", "Primitiva"],
  ["Oreja", "Primitiva"],
  ["Pez", "Primitiva"],
  ["Piedra", "Primitiva"],
  ["Río", "Primitiva"],
  ["Roca", "Primitiva"],
  ["Sangre", "Primitiva"],
  ["Tierra", "Primitiva"],
  ["Viento", "Primitiva"],
  ["Volcán", "Primitiva"],
  ["Mesa", "Primitiva"],
  ["Piso", "Primitiva"],
  ["Piedra", "Primitiva"],
  ["Luz", "Primitiva"],
  ["Tela", "Primitiva"],
  ["Casa", "Primitiva"],
  ["Planta", "Primitiva"],
  ["Cuerpo", "Primitiva"],
  ["Cabeza", "Primitiva"],
  ["Corazón", "Primitiva"],
  ["Luz", "Primitiva"],
  ["Tierra", "Primitiva"],
  ["Agua", "Primitiva"],
  ["Vida", "Primitiva"],
  ["Muerte", "Primitiva"],
  ["Mundo", "Primitiva"],
  ["Cielo", "Primitiva"],
  ["Árbol", "Primitiva"],
  ["Flor", "Primitiva"],
  ["Planta", "Primitiva"],
  ["Animal", "Primitiva"],
  ["Ojo", "Primitiva"],
  ["Boca", "Primitiva"],
  ["Mano", "Primitiva"],
  ["Pie", "Primitiva"],
  ["Sueño", "Primitiva"],
  ["Silla", "Primitiva"],
  ["Mesa", "Primitiva"],
  ["Comida", "Primitiva"],
  ["Bebida", "Primitiva"],
  ["lavaplatos", "Compuesta"],
  ["sacacorchos", "Compuesta"],
  ["guardabosques", "Compuesta"],
  ["pararrayos", "Compuesta"],
  ["lavamanos", "Compuesta"],
  ["salvavidas", "Compuesta"],
  ["guardabarros", "Compuesta"],
  ["Sillas", "Simple"],
  ["Niñas", "Simple"],
  ["Perros", "Simple"],
  ["Gatos", "Simple"],
  ["Casas", "Simple"],
  ["Árboles", "Simple"],
  ["Flores", "Simple"],
  ["Estrellas", "Simple"],
  ["Canciones", "Simple"],
  ["Caminos", "Simple"],
  ["Gafas", "Simple"],
  ["Puentes", "Simple"],
  ["Habitaciones", "Simple"],
  ["Cucharas", "Simple"],
  ["Sofás", "Simple"],
  ["Pisos", "Simple"],
  ["Bicicletas", "Simple"],
  ["Escuelas", "Simple"],
  ["Mujeres", "Simple"],
  ["Mamás", "Simple"],
  ["Abuelas", "Simple"],
  ["Hermanas", "Simple"],
  ["Amigas", "Simple"],
  ["Maestras", "Simple"],
  ["Doctoras", "Simple"],
  ["Científicas", "Simple"],
  ["Escritoras", "Simple"],
  ["Abuela", "Simple"],
  ["Hermana", "Simple"],
  ["Amiga", "Simple"],
  ["Maestra", "Simple"],
  ["Doctora", "Simple"],
  ["Científica", "Simple"],
  ["Escritora", "Simple"],
  ["Perchas", "Simple"],
  ["Lápices", "Simple"],
  ["Marcadores", "Simple"],
  ["Carpetas", "Simple"],
  ["Bombillas", "Simple"],
  ["Puertas", "Simple"],
  ["Ventanas", "Simple"],
  ["Sillas", "Simple"],
  ["Muebles", "Simple"],
  ["Pinturas", "Simple"],
  ["Plantas", "Simple"],
  ["Cuadros", "Simple"],
  ["Dientes", "Simple"],
  ["Médicos", "Simple"],
  ["Enfermeros", "Simple"],
  ["Pacientes", "Simple"],
  ["Policías", "Simple"],
  ["Bomberos", "Simple"],
  ["Soldados", "Simple"],
  ["Jueces", "Simple"],
  ["Profesores", "Simple"],
  ["Ingenieros", "Simple"],
  ["Cocineros", "Simple"],
  ["Pelotas", "Simple"],
  ["Piscinas", "Simple"],
  ["Relojes", "Simple"],
  ["Globos", "Simple"],
  ["Camisas", "Simple"],
  ["Zapatos", "Simple"],
  ["Sombreros", "Simple"],
  ["Juguetes", "Simple"],
  ["Muñecas", "Simple"],
  ["Autos", "Simple"],
  ["Cucharas", "Simple"],
  ["Tenedores", "Simple"],
  ["Cuchillos", "Simple"],
  ["Vasos", "Simple"],
  ["Platos", "Simple"],
  ["Cubiertos", "Simple"],
  ["Cestos", "Simple"],
  ["Pinceles", "Simple"],
  ["Esmaltes", "Simple"],
  ["Lentes", "Simple"],
  ["Audífonos", "Simple"],
  ["Cámaras", "Simple"],
  ["Computadoras", "Simple"],
  ["Monitores", "Simple"],
  ["Teclados", "Simple"],
  ["Ratones", "Simple"],
  ["Libretas", "Simple"],
  ["Cuadernos", "Simple"],
  ["Láminas", "Simple"],
  ["Pinceles", "Simple"],
  ["Pinturas", "Simple"],
  ["Lienzos", "Simple"],
  ["Marcos", "Simple"],
  ["Cajas", "Simple"],
  ["Bolsas", "Simple"],
  ["Cajones", "Simple"],
  ["Almohadas", "Simple"],
  ["Colchones", "Simple"],
  ["Sábanas", "Simple"],
  ["Mantas", "Simple"],
  ["Edredones", "Simple"],
  ["Barras", "Simple"],
  ["Discos", "Simple"],
  ["Mancuernas", "Simple"],
  ["Máquinas", "Simple"],
  ["Bicicletas", "Simple"],
  ["Patinetas", "Simple"],
  ["Triciclos", "Simple"],
  ["Coches", "Simple"],
  ["Barcos", "Simple"],
  ["Aviones", "Simple"],
  ["Helicópteros", "Simple"],
  ["Barcos", "Simple"],
  ["Globos aerostáticos", "Simple"],
  ["Satélites", "Simple"],
  ["Cohetes", "Simple"],
  ["Astronautas", "Simple"],
  ["Caramelos", "Simple"],
  ["Golosinas", "Simple"],
  ["Chicles", "Simple"],
  ["Dulces", "Simple"],
  ["Hamburguesas", "Simple"],
  ["Pizzas", "Simple"],
  ["Tacos", "Simple"],
  ["Sándwiches", "Simple"],
  ["Bocadillos", "Simple"],
  ["Fresas", "Simple"],
  ["Manzanas", "Simple"],
  ["Naranjas", "Simple"],
  ["Plátanos", "Simple"],
  ["Sandías", "Simple"],
  ["Melones", "Simple"],
  ["Piñas", "Simple"],
  ["Limones", "Simple"],
  ["Cerezas", "Simple"],
  ["Uvas", "Simple"],
  ["Papayas", "Simple"],
  ["Mangos", "Simple"],
  ["Aguacates", "Simple"],
  ["Arándanos", "Simple"],
  ["Frambuesas", "Simple"],
  ["gato", "primitiva"],
  ["perrito", "derivada"],
  ["corriendo", "simple"],
  ["corre", "simple"],
  ["saltando", "simple"],
  ["salta", "simple"],
  ["niña", "simple"],
  ["niños", "simple"],
  ["mesa", "primitiva"],
  ["mesita", "derivada"],
  ["bailando", "simple"],
  ["baila", "simple"],
  ["flores", "simple"],
  ["jugar", "simple"],
  ["jugando", "simple"],
  ["jugó", "simple"],
  ["león", "primitiva"],
  ["leones", "simple"],
  ["cantando", "simple"],
  ["canta", "simple"],
  ["casita", "derivada"],
  ["saltitos", "simple"],
  ["fumar", "simple"],
  ["fumando", "simple"],
  ["fumó", "simple"],
  ["corriendo", "simple"],
  ["corre", "simple"],
  ["saltando", "simple"],
  ["salta", "simple"],
  ["bailando", "simple"],
  ["baila", "simple"],
  ["jugar", "simple"],
  ["jugando", "simple"],
  ["jugó", "simple"],
  ["cantando", "simple"],
  ["canta", "simple"],
  ["fumar", "simple"],
  ["fumando", "simple"],
  ["fumó", "simple"],
  ["pensando", "simple"],
  ["piensa", "simple"],
  ["creyendo", "simple"],
  ["cree", "simple"],
  ["soñando", "simple"],
  ["sueña", "simple"],
  
  ["trabajando", "simple"],
  ["trabaja", "simple"],
  ["buscando", "simple"],
  ["busca", "simple"],
  ["riendo", "simple"],
  ["ríe", "simple"],
  ["comiendo", "simple"],
  ["come", "simple"],
  ["cantando", "simple"],
  ["canta", "simple"],
  ["bailando", "simple"],
  ["baila", "simple"],
  ["paseando", "simple"],
  ["pasea", "simple"],
  ["escuchando", "simple"],
  ["escucha", "simple"],
  ["viendo", "simple"],
  ["ve", "simple"],
  ["leyendo", "simple"],
  ["lee", "simple"],
  ["puentes", "simple"],
  ["colores", "simple"],
  ["flores", "simple"],
  ["botes", "simple"],
  ["gafas", "simple"],
  ["calles", "simple"],
  ["nieves", "simple"],
  ["camas", "simple"],
  ["dientes", "simple"],
  ["caras", "simple"],
  ["mentes", "simple"],
  ["cunas", "simple"],
  ["calzados", "simple"],
  ["sombras", "simple"],
  ["águilas", "simple"],
  ["rosales", "simple"],
  ["lentes", "simple"],
  ["damas", "simple"],
  ["trenzas", "simple"],
  ["cartas", "simple"],
  ["guitarras", "simple"],
  ["sombrillas", "simple"],
  ["monedas", "simple"],
  ["pizzas", "simple"],
  ["chaquetas", "simple"],
  ["maletas", "simple"],
  ["ventanas", "simple"],
  ["pantalones", "simple"],
  ["botellas", "simple"],
  ["bicicletas", "simple"],
  ["serpientes", "simple"],
  ["manzanas", "simple"],
  ["computadoras", "simple"],
  ["sándwiches", "simple"],
  ["sabanas", "simple"],
  ["zanahorias", "simple"],
  ["libélulas", "simple"],
  ["ratones", "simple"],
  ["pescados", "simple"],
  ["pelotas", "simple"],
  ["papayas", "simple"],
  ["cocodrilos", "simple"],
  ["mamuts", "simple"],
  ["aztecas", "simple"],
  ["vikingos", "simple"],
  ["piratas", "simple"],
  ["dinosaurios", "simple"],
  ["librero", "derivada"],
  ["librería", "derivada"],
  ["panadero", "derivada"],
  ["panadería", "derivada"],
  ["maestro", "derivada"],
  ["maestría", "derivada"],
  ["cantante", "derivada"],

  ["cantarín", "derivada"],
  ["canturrear", "derivada"],
  ["televisor", "derivada"],
  ["televisión", "derivada"],
  ["guitarra", "derivada"],
  ["guitarrita", "derivada"],
  ["futbolista", "derivada"],
  ["fútbol", "derivada"],
  ["corredor", "derivada"],
  ["carrera", "derivada"],
  ["carrerita", "derivada"],
  ["correría", "derivada"],
  ["correduría", "derivada"],
  ["corrida", "derivada"],
  ["corrediza", "derivada"],
  ["corredoría", "derivada"],
  ["corredera", "derivada"],
  ["café", "derivada"],
  ["cafetera", "derivada"],
  ["cafetal", "derivada"],
  ["cafetalero", "derivada"],
  ["cafetería", "derivada"],
  ["pescado", "derivada"],
  ["pescadero", "derivada"],
  ["pescadería", "derivada"],
  ["pescador", "derivada"],
  ["pescadillo", "derivada"],
  ["pescadilla", "derivada"],
  ["pescadito", "derivada"],
  ["pescadote", "derivada"],
  ["pescadilla", "derivada"],
  ["pescadoz", "derivada"],
  ["pescadumbre", "derivada"],
  ["pescadumbrejo", "derivada"],
  ["pescaíto", "derivada"],
  ["caminante", "derivada"],

  ["caminar", "derivada"],
  ["caminata", "derivada"],
  ["caminero", "derivada"],
  ["caminable", "derivada"],
  ["caminamiento", "derivada"],
  ["verde", "derivada"],
  ["verdecito", "derivada"],
  ["verdoso", "derivada"],
  ["verdura", "derivada"],
  ["verdurita", "derivada"],
  ["verdeante", "derivada"],
  ["verdecer", "derivada"],
  ["verdugón", "derivada"],
  ["verdulero", "derivada"],
  ["verdulería", "derivada"],
  ["verdear", "derivada"],
  ["gallina", "derivada"],
  ["gallinero", "derivada"],
  ["gallinaza", "derivada"],
  ["gallinita", "derivada"],
  ["gallardo", "derivada"],
  ["gallinaza", "derivada"],
  ["gallardón", "derivada"],
  ["gallinae", "derivada"],
  ["gallinejas", "derivada"],
  ["gallipato", "derivada"],
  ["gallardete", "derivada"],
  ["cuchillo", "primitiva"],
  ["cuchillada", "derivada"],
  ["cuchillero", "derivada"],
  ["cuchillada", "derivada"],
  ["cuchillero", "derivada"],
  ["cuchillar", "derivada"],
  ["cuchillero", "derivada"],
  ["cuchillazo", "derivada"],
  ["mesa", "primitiva"],
  ["mesita", "derivada"],
  ["mesilla", "derivada"],
  ["mesón", "derivada"],
  ["mesonero", "derivada"],
  ["mesote", "derivada"],
  ["mesura", "derivada"],
  ["mesurado", "derivada"],
  ["mesurado", "derivada"],
  ["mesuramiento", "derivada"],
  ["mesurar", "derivada"],
  ["mesura", "derivada"],
  ["mesurero", "derivada"],
  ["mesurón", "derivada"],
  ["mesurado", "derivada"],
  ["mesuradamente", "derivada"],
  ["mesuramiento", "derivada"],
  ["botella", "primitiva"],
  ["botellita", "derivada"],
  ["botellero", "derivada"],
  ["botellín", "derivada"],
  ["botellón", "derivada"],
  ["botellazo", "derivada"],
  ["botellar", "derivada"],
  ["botellero", "derivada"],
  ["botellón", "derivada"],
  ["botellazo", "derivada"],
  ["botica", "primitiva"],
  ["boticario", "derivada"],
  ["boticario", "derivada"],
  ["botiquín", "derivada"],
  ["botica", "derivada"],
  ["boticón", "derivada"],
  ["botijero", "derivada"],
  ["botijuela", "derivada"],
  ["botija", "derivada"],
  ["botijo", "derivada"],
  ["boca", "primitiva"],
  ["bocaza", "derivada"],
  ["bocacalle", "derivada"],
  ["bocadillo", "derivada"],
  ["bocado", "derivada"],
  ["bocajarro", "derivada"],
  ["bocata", "derivada"],
  ["bocatón", "derivada"],
  ["bocaza", "derivada"],
  ["boceto", "derivada"],
  ["bocio", "derivada"],
  ["bocón", "derivada"],
  ["bodegón", "derivada"],
  ["bodeguero", "derivada"],
  ["bodega", "derivada"],
  ["bodegón", "derivada"],
  ["bodegón", "derivada"],
  ["bodeguilla", "derivada"],
  ["bodega", "derivada"],
  ["bodeguero", "derivada"],
  ["bodega", "derivada"],
  ["bodegón", "derivada"],
  ["bodegón", "derivada"],
  ["bodeguilla", "derivada"],
  ["bodega", "derivada"],
  ["bodeguero", "derivada"],
  ["bombilla", "derivada"],
  ["bombillo", "derivada"],
  ["bombillazo", "derivada"],
  ["antivirus", "Compuesta"],
  ["autocorrector", "Compuesta"],
  ["reprogramar", "Derivada"],
  ["desordenado", "Derivada"],
  ["superhéroe", "Compuesta"],
  ["postdata", "Compuesta"],
  ["televidente", "Derivada"],
  ["enamoramiento", "Derivada"],
  ["desilusionado", "Derivada"],
  ["multimedia", "Compuesta"],
  ["transatlántico", "Compuesta"],
  ["desinformación", "Derivada"],
  ["injusticia", "Derivada"],
  ["sobrepasar", "Derivada"],
  ["posibilidad", "Derivada"],
  ["comprensivo", "Derivada"],
  ["Reutilización", "Derivada"],
  ["Inmadurez", "Derivada"],
  ["Desorganización", "Derivada"],
  ["Infelicidad", "Derivada"],
  ["Deslealtad", "Derivada"],
  ["Irresponsabilidad", "Derivada"],
  ["Inconsciente", "Derivada"],
  ["Antisocial", "Derivada"],
  ["Reconstrucción", "Derivada"],

  ["Desenfrenado", "Derivada"],
["Inexplicablemente", "Derivada"],
["Descuidadamente", "Derivada"],
["Reutilizable", "Derivada"],
["Inconscientemente", "Derivada"],
["Desesperadamente", "Derivada"],
["Atemporalidad", "Derivada"],
["Interminablemente", "Derivada"],
["Deslumbramiento", "Derivada"],

["Desanimo", "Derivada"],
["Reprochable", "Derivada"],
["Desarmar", "Derivada"],
["Descontento", "Derivada"],
["Resentimiento", "Derivada"],
["Desaparecido", "Derivada"],
["Desconfianza", "Derivada"],
["Recomendación", "Derivada"],
["Desencanto", "Derivada"],

["Despistado", "Derivada"],
["Reconstrucción", "Derivada"],
["Desenlace", "Derivada"],
["Resignación", "Derivada"],
["Desgastado", "Derivada"],
["Indisoluble", "Derivada"],
["Impenetrable", "Derivada"],
["Desaprobación", "Derivada"],
["Desacuerdo", "Derivada"],
["Reestructuración", "Derivada"],

["Desilusionado", "Derivada"],
["Reencarnación", "Derivada"],
["Desviación", "Derivada"],
["Desaparición", "Derivada"],
["Recalentamiento", "Derivada"],
["Desesperación", "Derivada"],
["Desfiguración", "Derivada"],
["Respetable", "Derivada"],
["Desobediencia", "Derivada"],
["Descomposición", "Derivada"],
["Resbaladizo", "Derivada"],


["Resplandeciente", "Derivada"],
["Reconocible", "Derivada"],


["Desvío", "Derivada"],

["Desenfocado", "Derivada"],
["Reincorporación", "Derivada"],
["Desinflar", "Derivada"],
["Desesperar", "Derivada"],
["Reconfortante", "Derivada"],

["Reeducación", "Derivada"],
["Reescritura", "Derivada"],
["Precalentamiento", "Derivada"],
["Zapatería", "Derivada"],
  ["Perezoso", "Derivada"],
  ["Canción", "Primitiva"],
  ["Cantante", "Derivada"],
  ["Pescadería", "Derivada"],
  ["Televisión", "Derivada"],
  ["Perro", "Primitiva"],
  ["Cortina", "Primitiva"],
  ["Cortinilla", "Derivada"],
  ["Piedra", "Primitiva"],
  ["Pedrusco", "Derivada"],
  ["Insoportable", "Parasintética por derivación"],
  ["Verdugo", "Derivada"],
  ["Amoroso", "Derivada"],
  ["Vestuario", "Compuesta"],
  ["Escritorio", "Compuesta"],
  ["Espectáculo", "Derivada"],
  ["Cajita", "Derivada"],
  ["Cajón", "Primitiva"],

  ["Comida", "Primitiva"],
  ["Cielo", "Primitiva"],
  ["Cielito", "Derivada"],
  ["Oveja", "Primitiva"],
  ["Ovejita", "Derivada"],
  ["Felino", "Derivada"],
  ["Felicidad", "Derivada"],
  ["Festejo", "Derivada"],
  ["Festejito", "Derivada"],
  ["Caracol", "Primitiva"],
  ["Caracolillo", "Derivada"],
  ["Dulce", "Primitiva"],
  ["Dulcería", "Derivada"],
  ["Mentiroso", "Derivada"],
  ["Mentira", "Primitiva"],
  ["Flor", "Primitiva"],
  ["Florero", "Derivada"],
  ["Pájaro", "Primitiva"],
  ["Pajarillo", "Derivada"],
  ["Mujer", "Primitiva"],
  ["Mujeriego", "Derivada"],
  ["Jardín", "Primitiva"],
  ["Jardinero", "Derivada"],
  ["Música", "Primitiva"],
  ["Músico", "Derivada"],
  ["Cafetería", "Derivada"],
  ["Café", "Primitiva"],
  ["Biblioteca", "Derivada"],
  ["Libro", "Primitiva"],
  ["Cine", "Primitiva"],
  ["Cinematógrafo", "Derivada"],
  ["Cuchillo", "Primitiva"],
  ["Cuchillito", "Derivada"],
  ["Futbolista", "Derivada"],
  ["Fútbol", "Primitiva"],
  ["Rey", "Primitiva"],
  ["Reyecito", "Derivada"],
  ["Microondas", "Compuesta"],
  ["Sillita", "derivada"],
  ["Pastelito", "derivada"],
  ["Caminante", "derivada"],
  ["Jardinero", "derivada"],
  ["Librería", "derivada"],
  ["Caminata", "derivada"],
  ["Bailarín", "derivada"],
  ["Pintura", "derivada"],
  ["Lechera", "derivada"],
  ["Gallinero", "derivada"],
  ["Casita", "derivada"],
  ["Aguacate", "derivada"],
  ["Reyerta", "derivada"],
  ["Corredor", "derivada"],
  ["Cocinita", "derivada"],
  ["Lectora", "derivada"],
  ["Pescador", "derivada"],
  ["Gallina", "derivada"],
  ["Perrito", "derivada"],
  ["Pescadito", "derivada"],
  ["Comedor", "derivada"],
  ["Cantante", "derivada"],
  ["Barquito", "derivada"],
  ["Bailarina", "derivada"],
  ["Agujero", "derivada"],
  ["Campesino", "derivada"],
  ["Cazador", "derivada"],
  ["Pastor", "derivada"],
  ["Navegante", "derivada"],
  ["Escritora", "derivada"],
  ["Maestra", "derivada"],
  ["Corredora", "derivada"],
  ["Trenza", "derivada"],
  ["Pintor", "derivada"],
  ["Gatito", "derivada"],
  ["Lechería", "derivada"],
  ["Jugadora", "derivada"],
  ["Perrita", "derivada"],
  ["Oveja", "derivada"],
  ["Cocinero", "derivada"],
  ["Vendedor", "derivada"],
  ["Luchador", "derivada"],
  ["Cocinera", "derivada"],
  ["Nadador", "derivada"],
  ["Estudiante", "derivada"],
  ["Pescadora", "derivada"],
  ["Bebé", "derivada"],
  ["Escritor", "derivada"],
  ["Cazadora", "derivada"],
  ["Camionero", "derivada"],
  ["Lavaplatos", "derivada"],
  ["Pastelería", "derivada"],
  ["Agujita", "derivada"],
  ["Biblioteca", "derivada"],
  ["Médico", "derivada"],
  ["Película", "derivada"],
  ["Gallinera", "derivada"],
  ["Pintura", "derivada"],
  ["Caminadora", "derivada"],
  ["Pescadito", "derivada"],
  ["Bebé", "derivada"],
  ["Librero", "derivada"],
  ["Maestro", "derivada"],
  ["Vendedor", "derivada"],
  ["Luchadora", "derivada"],
  ["Cocinera", "derivada"],
  ["Nadadora", "derivada"],
  ["Estudio", "derivada"],
  ["Pescador", "derivada"],
  ["Jugadora", "derivada"],
  ["Biblioteca", "derivada"],
  ["Gallinero", "derivada"],
  ["Pastelería", "derivada"],
  ["enchufable", "parasintética por derivación"],
  ["desesperante", "parasintética por derivación"],
  ["huesudo", "derivada"],
  ["cantarín", "derivada"],
  ["bailarina", "derivada"],
  ["cantante", "derivada"],
  ["molinillo", "derivada"],
  ["lavandería", "derivada"],
  ["escritorio", "derivada"],
  ["campesino", "derivada"],
  ["perezoso", "derivada"],
  ["carretera", "derivada"],
  ["botoncito", "derivada"],
  ["corazón", "derivada"],
  ["alucinante", "derivada"],
  ["aburrimiento", "derivada"],
  ["cariñoso", "derivada"],
  ["revoltoso", "derivada"],
  ["canturrear", "derivada"],
  ["saltarín", "derivada"],
  ["callejón", "derivada"],
  ["pararrayos", "compuesta"],
  ["baloncesto", "compuesta"],
  ["guardabosques", "compuesta"],
  ["lavaplatos", "compuesta"],
  ["pasamontañas", "compuesta"],
  ["pelirrojo", "compuesta"],
  ["salvavidas", "compuesta"],
  ["rompecabezas", "compuesta"],
  ["mediodía", "compuesta"],
  ["girasol", "compuesta"],
  ["limpiabotas", "compuesta"],
  ["sacacorchos", "compuesta"],
  ["limpiaparabrisas", "compuesta"],
  ["sabelotodo", "compuesta"],
  ["limpiacristales", "compuesta"],
  ["guardacoches", "compuesta"],
  ["matahombres", "compuesta"],
  ["atrapasueños", "compuesta"],
  ["abrelatas", "compuesta"],
  ["quitamanchas", "compuesta"],
  ["paracaídas", "compuesta"],
  ["baloncesto", "compuesta"],
  ["sacapuntas", "compuesta"],
  ["guardacostas", "compuesta"],
  ["lavaplatos", "compuesta"],
  ["rompecabezas", "compuesta"],
  ["guardabosques", "compuesta"],
  ["matamoscas", "compuesta"],
  ["rompevientos", "compuesta"],
  ["cazatalentos", "compuesta"],
  ["rascacielos", "compuesta"],
  ["quitamanchas", "compuesta"],
  ["cortafuegos", "compuesta"],
  ["salvavidas", "compuesta"],
  ["pasamontañas", "compuesta"],
  ["cortaúñas", "compuesta"],
  ["sobretodo", "compuesta"],
  ["limpiacristales", "compuesta"],
  ["pararrayos", "compuesta"],
  ["sacacorchos", "compuesta"],
  ["rompecabezas", "compuesta"],
  ["guardabosques", "compuesta"],
  ["matamoscas", "compuesta"],
  ["rompevientos", "compuesta"],
  ["cazatalentos", "compuesta"],
  ["rascacielos", "compuesta"],
  ["quitamanchas", "compuesta"],
  ["cortafuegos", "compuesta"],
  ["salvavidas", "compuesta"],
  ["pasamontañas", "compuesta"],
  ["cortaúñas", "compuesta"],
  ["sobretodo", "compuesta"],
  ["limpiacristales", "compuesta"],
  ["pararrayos", "compuesta"],
  ["sacacorchos", "compuesta"],
  ["comecocos", "compuesta"],
  ["girasol", "compuesta"],
  ["guardapolvo", "compuesta"],
  ["pelirrojo", "compuesta"],
  ["quitamiedos", "compuesta"],
  ["salvavidas", "compuesta"],
  ["sordomudo", "compuesta"],
  ["pararrayos", "compuesta"],
  ["limpiafondos", "compuesta"],

  ["matrimonio", "compuesta"],
  ["portamonedas", "compuesta"],
  ["lanzallamas", "compuesta"],
  ["aguardiente", "compuesta"],
  ["rompecorazones", "compuesta"],
  ["guardabarros", "compuesta"],
  ["cortaespárragos", "compuesta"],
  ["paraguas", "compuesta"],
  ["quitapenas", "compuesta"],
  ["quitaesmalte", "compuesta"],
  ["saltamontes", "compuesta"],
  ["parabrisas", "compuesta"],
  ["guardamuebles", "compuesta"],
  ["cortinillas", "compuesta"],
  ["salvapantallas", "compuesta"],
  ["portaplumas", "compuesta"],
  ["guardaespaldas", "compuesta"],
["paraguas", "compuesta"],
["rascacielos", "compuesta"],
["salvavidas", "compuesta"],
["sacacorchos", "compuesta"],
["lavavajillas", "compuesta"],
["altavoz", "compuesta"],
["pasatiempo", "compuesta"],
["rompecabezas", "compuesta"],
["sabelotodo", "compuesta"],
["limpiabotas", "compuesta"],
["guardabosques", "compuesta"],
  ["sacacorchos", "compuesta"],
  ["pasamontañas", "compuesta"],
  ["sacapuntas", "compuesta"],
  ["rompecabezas", "compuesta"],
  ["mariposa", "compuesta"],
  ["salvavidas", "compuesta"],
  ["parachoques", "compuesta"],
  ["lavaplatos", "compuesta"],
  ["rascacielos", "compuesta"],
  ["guardacostas", "compuesta"],
  ["cortacésped", "compuesta"],
  ["pararrayos", "compuesta"],
  ["guardaespaldas", "compuesta"],
  ["portaviones", "compuesta"],
  ["parabrisas", "compuesta"],
  ["pelirrojo", "compuesta"],
  ["matahari", "compuesta"],
  ["salvapantallas", "compuesta"],
  ["sacaleches", "compuesta"],
  ["quitamanchas", "compuesta"],
  ["sacabocados", "compuesta"],
  ["matamoscas", "compuesta"],
  ["sacapapeles", "compuesta"],
  ["cortafuegos", "compuesta"],
  ["portafolio", "compuesta"],
  ["lavamanos", "compuesta"],
  ["rompecorazones", "compuesta"],
  ["guardarropa", "compuesta"],
  ["pasacalles", "compuesta"],
  ["guardapolvo", "compuesta"],
  ["abrebotellas", "compuesta"],
  ["sacudidor", "compuesta"],
  ["limpiacristales", "compuesta"],
  ["quitaesmalte", "compuesta"],
  ["peluquín", "compuesta"],
  ["paracaidas", "compuesta"],
  ["guardaníquel", "compuesta"],
  ["picaflor", "compuesta"],
  ["cortaúñas", "compuesta"],
  ["lustrabotas", "compuesta"],
  ["pasatiempo", "compuesta"],
  ["lavavajillas", "compuesta"],
  ["matapiojos", "compuesta"],
  ["sacatrapos", "compuesta"],
  ["abrelatas", "compuesta"],
  ["paraguas", "compuesta"],
  ["guardavías", "compuesta"],
  ["sacamuelas", "compuesta"],
  ["portaplumas", "compuesta"],
  ["quitapenas", "compuesta"],
  ["sacapuntas", "compuesta"],
  ["lavaplatos", "compuesta"],
  ["rompecabezas", "compuesta"],
  ["pararrayos", "compuesta"],
  ["guardaespaldas", "compuesta"],
  ["mariposa", "compuesta"],
  ["rascacielos", "compuesta"],
  ["pelirrojo", "compuesta"],
  ["salvavidas", "compuesta"],
  ["sacaleches", "compuesta"],
  ["matahari", "compuesta"],
  ["pasamuros", "compuesta"],
  ["portavoz", "compuesta"],
  ["cortina", "compuesta"],
  ["lavapies", "compuesta"],
  ["rompecorazones", "compuesta"],
  ["Desalmado", "parasintética por derivación"],
  ["Desesperado", "parasintética por derivación"],
  ["Enloquecido", "parasintética por derivación"],
  ["Desfavorecido", "parasintética por derivación"],
  ["Enriquecido", "parasintética por derivación"],
  ["Enternecedor", "parasintética por derivación"],
  ["Empobrecido", "parasintética por derivación"],
  ["Desfigurado", "parasintética por derivación"],
  ["Ensangrentado", "parasintética por derivación"],
  ["Deslumbrado", "parasintética por derivación"],
  ["Engañado", "parasintética por derivación"],
  ["Desorientado", "parasintética por derivación"],
  ["Emocionado", "parasintética por derivación"],
  ["Desaprobado", "parasintética por derivación"],
  ["Enamorado", "parasintética por derivación"],
  ["Desacostumbrado", "parasintética por derivación"],
  ["Enfurecido", "parasintética por derivación"],
  ["Desagradable", "parasintética por derivación"],
  ["Envejecido", "parasintética por derivación"],
  ["Desgarrado", "parasintética por derivación"],
  ["Entumecido", "parasintética por derivación"],
  ["Desilusionado", "parasintética por derivación"],
  ["Engreído", "parasintética por derivación"],
  ["Desarmado", "parasintética por derivación"],
  ["Endulzado", "parasintética por derivación"],
  ["Desentendido", "parasintética por derivación"],
  ["Engordado", "parasintética por derivación"],
  ["Desconsolado", "parasintética por derivación"],
  ["Enredado", "parasintética por derivación"],
  ["Desconcertado", "parasintética por derivación"],
  ["Enamoramiento", "parasintética por derivación"],
  
  ["Desalmado", "Parasintética por derivación"],
  ["Desabrigado", "Parasintética por derivación"],
  ["Despertador", "Parasintética por derivación"],
  ["Desconocido", "Parasintética por derivación"],

  ["Desempleado", "Parasintética por derivación"],
  ["Enterrador", "Parasintética por derivación"],
  ["Entristecedor", "Parasintética por derivación"],
  ["Empobrecido", "Parasintética por derivación"],
  ["Enriquecedor", "Parasintética por derivación"],
  ["Encantador", "Parasintética por derivación"],
  ["Engañador", "Parasintética por derivación"],
  ["Iluminado", "Parasintética por derivación"],
  ["Enloquecido", "Parasintética por derivación"],
  ["Endurecido", "Parasintética por derivación"],
  ["Empequeñecido", "Parasintética por derivación"],
  ["Empapado", "Parasintética por derivación"],
  ["Desenfrenado", "Parasintética por derivación"],
  ["Deslumbrante", "Parasintética por derivación"],
  ["Desesperado", "Parasintética por derivación"],
  ["Desconcertado", "Parasintética por derivación"],
  ["Desanimado", "Parasintética por derivación"],
  ["Deslenguado", "Parasintética por derivación"],
  ["Desenmascarado", "Parasintética por derivación"],
  ["Desilusionado", "Parasintética por derivación"],
  ["Desmejorado", "Parasintética por derivación"],
  ["Desnaturalizado", "Parasintética por derivación"],
  ["Desorganizado", "Parasintética por derivación"],
  ["Despistado", "Parasintética por derivación"],
  ["Desgarrador", "Parasintética por derivación"],
  ["Desatado", "Parasintética por derivación"],
  ["Desubicado", "Parasintética por derivación"],
  ["Desvencijado", "Parasintética por derivación"],

  ["Desenfadado", "Parasintética por derivación"],
  ["Desorbitado", "Parasintética por derivación"],
  ["Despiadado", "Parasintética por derivación"],
  ["Deslizado", "Parasintética por derivación"],
  ["Desintegrado", "Parasintética por derivación"],
  ["Desnudado", "Parasintética por derivación"],
  ["Desollado", "Parasintética por derivación"],
  ["Desobediente", "Parasintética por derivación"],
  ["Desinformado", "Parasintética por derivación"],
  ["Desarmado", "Parasintética por derivación"],
  ["Desencantado", "Parasintética por derivación"],
  ["Desagradable", "Parasintética por derivación"],
];



function Act6Cast({ correcting, language, actID }) {
  const [fig, setfig] = useState(
    dataCAST[Math.floor(Math.random() * dataCAST.length)]
  );
  const [selected, setSelected] = useState("Escull una opció!");

  const correctanswer = fig[1];

  var options = [];
  dataCAST.forEach((element) => {
    if (!options.includes(element[1])) options.push(element[1]);
  });

  const [ops, setOps] = useState(
    [correctanswer]
      .concat(
        [...options].sort(() => (Math.random() > 0.5 ? 1 : -1)).slice(0, 2)
      )
      .sort(() => Math.random() - 0.5)
  );
  return (
    <Component>
      {" "}
      <b>{fig[0]}</b>
      <br />
      <div
        className="options-component"
        onChange={(e) => {
          setSelected(e.target.value);
        }}
      >
        {ops.map((element, i) => {
          return (
            <>
              <input
                checked={element == selected}
                value={element}
                type="radio"
                name={"ex" + actID.toString()}
                id={i.toString() + "-" + actID.toString()}
                disabled={correcting}
              />
              <label
                className={
                  correcting && selected != "Escull una opció!"
                    ? correctanswer == selected
                      ? "correct-answ"
                      : "wrong-answ"
                    : ""
                }
                htmlFor={i.toString() + "-" + actID.toString()}
              >
                {element}
              </label>
            </>
          );
        })}
      </div>
    </Component>
  );
}

const Component = styled.div`
  margin-top: 1.4rem;
  margin-bottom: 1.4rem;
  margin-left: 1.5rem;
  width: 30vw;
  @media (min-width: 1100px) {
    margin-left: 3rem;
    width: 30vw;
  }
  @media (max-width: 700px) {
    margin-left: 1rem;
    width: 20vw;
  }

  .correct-answ {
    color: green;
  }

  .wrong-answ {
    color: red;
  }

  input {
    margin-right: 0.5rem;
  }
  label {
    transition: all 150ms ease;
    margin-right: 1rem;
  }
  .options-component {
    margin-top: 0.4rem;
  }
`;

export default Act6Cast;
